# Generated by Django 4.1.2 on 2022-11-28 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'condition',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('age', models.IntegerField()),
                ('k', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('phos', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('na', models.IntegerField(blank=True)),
                ('creatinine', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('albumin', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('bloodsugar', models.IntegerField(blank=True)),
                ('condition', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kidneytracker.condition')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=30)),
                ('measurement', models.CharField(max_length=30)),
                ('sodium', models.IntegerField()),
                ('protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('water', models.DecimalField(decimal_places=2, max_digits=5)),
                ('k', models.IntegerField()),
                ('phos', models.IntegerField()),
            ],
            options={
                'db_table': 'nutrients',
                'unique_together': {('food', 'measurement')},
            },
        ),
        migrations.CreateModel(
            name='journal_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField()),
                ('meal_type', models.CharField(max_length=30)),
                ('nutrients', models.ManyToManyField(to='kidneytracker.nutrient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kidneytracker.user')),
            ],
            options={
                'db_table': 'journal_entry',
            },
        ),
    ]
