# Generated by Django 4.1.2 on 2022-11-29 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kidneytracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kidneytracker.condition'),
        ),
    ]
