# Generated by Django 4.1.2 on 2022-11-30 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidneytracker', '0002_alter_user_condition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nutrient',
            unique_together=set(),
        ),
    ]
